# Operations on np arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([67,23,83,20])



In [3]:
num = 4

res = arr + num

print(res)

[71 27 87 24]


In [4]:
res = num * arr
print(res)

[268  92 332  80]


In [5]:
res = arr // 4
print(res)

[16  5 20  5]


In [6]:
matrix = np.array(
    [
        [3,2,5],
        [7,8,9],
        [9,3,2]
    ]
)

print(matrix * num)

[[12  8 20]
 [28 32 36]
 [36 12  8]]


If we have any scalar value and if you perform operation using . so each element of the matrix or array going to be the part of that operation(broadcast).

## inbuilt functions for arrays

In [8]:
arr

array([67, 23, 83, 20])

In [7]:
arr.sum()

np.int64(193)

In [9]:
np.sum(arr)

np.int64(193)

In [10]:
np.mean(arr)

np.float64(48.25)

In [11]:
np.std(arr)

np.float64(27.36215452043205)

In [12]:
np.var(arr)

np.float64(748.6875)

In [14]:
arr

array([67, 23, 83, 20])

[67, 90, 173, 193]

In [13]:
np.cumsum(arr)

array([ 67,  90, 173, 193])

In [15]:
np.prod(arr)

np.int64(2558060)

In [16]:
np.cumprod(arr)

array([     67,    1541,  127903, 2558060])

In [17]:
matrix

array([[3, 2, 5],
       [7, 8, 9],
       [9, 3, 2]])

In [18]:
np.sum(matrix)

np.int64(48)

axis=0 , means you are adding the rows.

In [19]:
np.sum(matrix,axis=0)

array([19, 13, 16])

axis=1, means you are adding columns.

In [20]:
np.sum(matrix,axis=1)

array([10, 24, 14])

In [21]:
np.mean(matrix,axis=0)

array([6.33333333, 4.33333333, 5.33333333])

In [22]:
np.mean(matrix,axis=1)

array([3.33333333, 8.        , 4.66666667])

In [24]:
mat = np.array(
    [
        [3,4,5],
        [2,8,6],
        [4,5,3]
    ]
)
np.sum(mat,axis=1)

array([12, 16, 12])

In [26]:
arr

array([67, 23, 83, 20])

In [25]:
np.max(arr)

np.int64(83)

In [27]:
np.min(arr)

np.int64(20)

In [33]:
mat

array([[3, 4, 5],
       [2, 8, 6],
       [4, 5, 3]])

In [31]:
np.max(mat)

np.int64(8)

In [34]:
np.max(mat,axis=1)

array([5, 8, 5])

In [35]:
np.min(mat,axis=1)


array([3, 2, 3])

# Broadcasting

In [36]:
arr * 2

array([134,  46, 166,  40])

In [38]:
arr.shape

(4,)

In [39]:
np.array([2,2,2,2]).shape

(4,)

In [41]:
arr

array([67, 23, 83, 20])

In [40]:
arr * np.array([2,2,2,2])

array([134,  46, 166,  40])

In [42]:
matrix

array([[3, 2, 5],
       [7, 8, 9],
       [9, 3, 2]])

In [45]:
matrix.shape

(3, 3)

In [44]:
matrix * np.array([
    [2,2,2],
    [2,2,2],
    [2,2,2]
])

array([[ 6,  4, 10],
       [14, 16, 18],
       [18,  6,  4]])

In [46]:
matrix

array([[3, 2, 5],
       [7, 8, 9],
       [9, 3, 2]])

In [47]:
mat = np.array([3,2,4])

print(matrix * mat)

[[ 9  4 20]
 [21 16 36]
 [27  6  8]]


In [48]:
matrix.shape

(3, 3)

In [50]:
mat.shape

matrix*np.array([[3,2,4],
[3,2,4],
[3,2,4]])

array([[ 9,  4, 20],
       [21, 16, 36],
       [27,  6,  8]])

In [51]:
cl = np.array(
    [
        [2],
        [3],
        [5]
    ]
)

In [55]:
matrix

array([[3, 2, 5],
       [7, 8, 9],
       [9, 3, 2]])

In [54]:
matrix * cl

array([[ 6,  4, 10],
       [21, 24, 27],
       [45, 15, 10]])

In [56]:
matrix

array([[3, 2, 5],
       [7, 8, 9],
       [9, 3, 2]])

In [57]:
matrix.T

array([[3, 7, 9],
       [2, 8, 3],
       [5, 9, 2]])

In [60]:
matrix @ matrix

array([[ 68,  37,  43],
       [158, 105, 125],
       [ 66,  48,  76]])

In [61]:
matrix.dot(matrix)

array([[ 68,  37,  43],
       [158, 105, 125],
       [ 66,  48,  76]])

In [63]:
matrix

array([[3, 2, 5],
       [7, 8, 9],
       [9, 3, 2]])

In [62]:
matrix.flatten()

array([3, 2, 5, 7, 8, 9, 9, 3, 2])