# Numpy - Numerical Python

We use numpy to do numerical calculations, scaler and vectors calculations.

In [2]:
pip install numpy 

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 26.1 MB/s  0:00:00m0:00:010:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
arr = np.array([34,23,45,56,34])
print(arr)

[34 23 45 56 34]


In [7]:
lst = [34,89,78,49]
arr1 = np.array(lst)


print("Numpy array: ",arr1)
print("Standard python list: ",lst)
print("Numpy array type: ",type(arr1))
print("Type of list: ",type(lst))

Numpy array:  [34 89 78 49]
Standard python list:  [34, 89, 78, 49]
Numpy array type:  <class 'numpy.ndarray'>
Type of list:  <class 'list'>


In [9]:
arr1 * 2

array([ 68, 178, 156,  98])

In [13]:
import time


num = 10_00_000
# [0 - 999999] x 2

lst = list(range(num))

start = time.time()
print(start," start the list operation")
result = [x * 2 for x in lst]
end = time.time()
print(end," end the list operation")
print("List operation time: ",(end - start)*100)


arr = np.arange(num)
start = time.time()
print(start," start the np operation")
result = arr * 2
end = time.time()
print(end," end the np operation")
print("Numpy array time: ",(end - start)*100)





1788707281.2260292  start the list operation
1788707281.2652931  end the list operation
List operation time:  3.926396369934082
1788707281.2659965  start the np operation
1788707281.2750087  end the np operation
Numpy array time:  0.9012222290039062


## Creating the array in numpy

In [16]:
arr = np.array([34,23,53,23,45])
print(arr)

[34 23 53 23 45]


In [17]:
matrix = np.array([
    [23,34,45],
    [34,78,23],
    [45,89,90]
])

print(matrix," \ntype: ",type(matrix))


[[23 34 45]
 [34 78 23]
 [45 89 90]]  
type:  <class 'numpy.ndarray'>


In [19]:
print(arr.ndim)
print(matrix.ndim)

1
2


In [22]:
print(arr.shape)
print(matrix.shape)

(5,)
(3, 3)


In [23]:
mat = np.array([
    [2,3],
    [4,5],
    [9,2]
])
print(mat)
print(mat.shape)

[[2 3]
 [4 5]
 [9 2]]
(3, 2)


In [24]:
mat.size

6

In [25]:
matrix.size

9

In [26]:
arr.size

5

In [27]:
matrix.dtype

dtype('int64')

## Array of zero

In [ ]:
np.zeros(5) # 1 dimension array

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((3,3)) # 2 dimension array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,2,3)) # 3D array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Array of one

In [33]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

## Empty array

In [37]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## linspace

In [41]:
np.linspace(-1,1,10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

## aranage

In [43]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])