In [97]:
import numpy as np

In [98]:
np.random.seed(42)

## Dataset

- 100 employees
- 6 months
- 4 region
- 5 products

# Numerical Data

In [99]:
n = 100

employee_id = np.arange(1001,1001 + n)
age = np.random.randint(22,55,n)
experience = np.random.randint(0,16,n)
sales = np.random.randint(20000,150000,n)
units_sold = np.random.randint(20,100,n)
discount = np.round(np.random.uniform(0,30,n),2)
customer_rating = np.round(np.random.uniform(2.5,5,n),2)


## Categorical Data

In [100]:
regions = np.random.choice(
    ["North","South","East","West"],
    n
)

products = np.random.choice(
    ["Laptop","Mobile","Tablet","Monitor","Printer"],
    n
)

In [101]:
regions

array(['East', 'North', 'North', 'South', 'South', 'East', 'West', 'East',
       'North', 'East', 'West', 'South', 'West', 'West', 'West', 'South',
       'West', 'West', 'West', 'North', 'West', 'South', 'West', 'West',
       'South', 'West', 'South', 'West', 'South', 'West', 'West', 'North',
       'North', 'West', 'West', 'East', 'South', 'East', 'North', 'North',
       'North', 'North', 'West', 'North', 'West', 'West', 'North',
       'North', 'South', 'East', 'North', 'South', 'South', 'East',
       'West', 'North', 'East', 'North', 'South', 'South', 'West',
       'South', 'South', 'East', 'North', 'North', 'East', 'West',
       'North', 'South', 'North', 'South', 'West', 'East', 'North',
       'East', 'North', 'South', 'East', 'North', 'South', 'East', 'East',
       'North', 'North', 'North', 'South', 'North', 'East', 'East',
       'North', 'North', 'West', 'East', 'South', 'West', 'North',
       'North', 'East', 'North'], dtype='<U5')

In [102]:
products

array(['Tablet', 'Printer', 'Printer', 'Printer', 'Printer', 'Mobile',
       'Mobile', 'Tablet', 'Laptop', 'Printer', 'Laptop', 'Laptop',
       'Tablet', 'Printer', 'Printer', 'Monitor', 'Laptop', 'Laptop',
       'Mobile', 'Monitor', 'Mobile', 'Mobile', 'Mobile', 'Tablet',
       'Tablet', 'Mobile', 'Monitor', 'Laptop', 'Monitor', 'Printer',
       'Tablet', 'Laptop', 'Laptop', 'Printer', 'Printer', 'Mobile',
       'Tablet', 'Tablet', 'Monitor', 'Mobile', 'Mobile', 'Mobile',
       'Mobile', 'Tablet', 'Tablet', 'Mobile', 'Monitor', 'Laptop',
       'Laptop', 'Monitor', 'Mobile', 'Tablet', 'Laptop', 'Printer',
       'Printer', 'Monitor', 'Mobile', 'Laptop', 'Mobile', 'Laptop',
       'Monitor', 'Monitor', 'Printer', 'Mobile', 'Printer', 'Mobile',
       'Printer', 'Tablet', 'Tablet', 'Tablet', 'Tablet', 'Laptop',
       'Tablet', 'Monitor', 'Monitor', 'Laptop', 'Tablet', 'Tablet',
       'Tablet', 'Printer', 'Mobile', 'Printer', 'Mobile', 'Tablet',
       'Tablet', 'Printer', 'Prin

In [103]:
data = np.zeros(n,
dtype=[
    ("Employee_id",'i4'),
    ("Age",'i4'),
    ("Experience",'i4'),
    ("Region","U10"),
    ("Product","U15"),
    ("Sales","f8"),
    ("Unit_sold","i4"),
    ("Discount","f8"),
    ("Customer_Rating","f8")
])

Now populate data:

In [104]:
data['Employee_id'] = employee_id
data['Age'] = age
data['Experience'] = experience
data['Region'] = regions
data['Product'] = products
data['Sales'] = sales
data['Unit_sold'] = units_sold
data['Discount'] = discount
data['Customer_Rating'] = customer_rating

In [105]:
data[:5]

array([(1001, 50,  2, 'East', 'Tablet',  58623., 52, 11.27, 4.07),
       (1002, 36, 14, 'North', 'Printer',  27392., 43,  2.82, 4.69),
       (1003, 29, 15, 'North', 'Printer',  75680., 94, 17.35, 4.34),
       (1004, 42,  6, 'South', 'Printer', 146354., 91,  1.08, 4.51),
       (1005, 40,  0, 'South', 'Printer',  66717., 55, 13.97, 3.21)],
      dtype=[('Employee_id', '<i4'), ('Age', '<i4'), ('Experience', '<i4'), ('Region', '<U10'), ('Product', '<U15'), ('Sales', '<f8'), ('Unit_sold', '<i4'), ('Discount', '<f8'), ('Customer_Rating', '<f8')])

How many records are there?


In [106]:
len(data)

100

Column names

In [107]:
data.dtype.names

('Employee_id',
 'Age',
 'Experience',
 'Region',
 'Product',
 'Sales',
 'Unit_sold',
 'Discount',
 'Customer_Rating')

Select the column

In [108]:
data['Sales'][:10]

array([ 58623.,  27392.,  75680., 146354.,  66717., 139937., 107092.,
        70859., 145657., 124095.])

Total Sales

In [109]:
np.sum(data['Sales'])

np.float64(8471293.0)

In [110]:
np.mean(data['Sales'])

np.float64(84712.93)

In [111]:
np.min(data['Sales'])

np.float64(21802.0)

In [112]:
np.max(data['Sales'])

np.float64(146603.0)

In [113]:
np.median(data['Sales'])

np.float64(86211.5)

In [114]:
np.std(data['Sales'])

np.float64(38575.65365596674)

In [115]:
np.var(data['Sales'])

np.float64(1488081054.9851)

In [116]:
data[0]

np.void((1001, 50, 2, 'East', 'Tablet', 58623.0, 52, 11.27, 4.07), dtype=[('Employee_id', '<i4'), ('Age', '<i4'), ('Experience', '<i4'), ('Region', '<U10'), ('Product', '<U15'), ('Sales', '<f8'), ('Unit_sold', '<i4'), ('Discount', '<f8'), ('Customer_Rating', '<f8')])

In [117]:
data[-1]

np.void((1100, 34, 4, 'North', 'Mobile', 146071.0, 34, 20.9, 4.24), dtype=[('Employee_id', '<i4'), ('Age', '<i4'), ('Experience', '<i4'), ('Region', '<U10'), ('Product', '<U15'), ('Sales', '<f8'), ('Unit_sold', '<i4'), ('Discount', '<f8'), ('Customer_Rating', '<f8')])

In [118]:
data[:10]

array([(1001, 50,  2, 'East', 'Tablet',  58623., 52, 11.27, 4.07),
       (1002, 36, 14, 'North', 'Printer',  27392., 43,  2.82, 4.69),
       (1003, 29, 15, 'North', 'Printer',  75680., 94, 17.35, 4.34),
       (1004, 42,  6, 'South', 'Printer', 146354., 91,  1.08, 4.51),
       (1005, 40,  0, 'South', 'Printer',  66717., 55, 13.97, 3.21),
       (1006, 44,  3, 'East', 'Mobile', 139937., 57, 16.28, 2.94),
       (1007, 32, 12, 'West', 'Mobile', 107092., 44,  8.6 , 4.38),
       (1008, 32, 15, 'East', 'Tablet',  70859., 37, 17.72, 4.52),
       (1009, 45,  3, 'North', 'Laptop', 145657., 85,  0.92, 4.98),
       (1010, 45, 13, 'East', 'Printer', 124095., 73,  1.12, 3.53)],
      dtype=[('Employee_id', '<i4'), ('Age', '<i4'), ('Experience', '<i4'), ('Region', '<U10'), ('Product', '<U15'), ('Sales', '<f8'), ('Unit_sold', '<i4'), ('Discount', '<f8'), ('Customer_Rating', '<f8')])

In [119]:
data[20:30]

array([(1021, 46,  6, 'West', 'Mobile',  57157., 39, 16.22, 3.76),
       (1022, 48, 10, 'South', 'Mobile',  87863., 27, 19.12, 4.57),
       (1023, 49,  2, 'West', 'Mobile', 126308., 26, 21.78, 3.3 ),
       (1024, 37,  5, 'West', 'Tablet',  72083., 86, 29.28, 4.74),
       (1025, 36, 11, 'South', 'Tablet', 126081., 36, 15.49, 3.47),
       (1026, 24,  1, 'West', 'Mobile',  85733., 52,  9.69, 2.53),
       (1027, 28,  9, 'South', 'Monitor', 109045., 67, 23.86, 4.76),
       (1028, 42, 12, 'West', 'Laptop',  54698., 95,  8.12, 2.73),
       (1029, 30, 13, 'South', 'Monitor', 130078., 78, 13.17, 3.3 ),
       (1030, 39,  8, 'West', 'Printer', 100623., 41,  2.35, 4.88)],
      dtype=[('Employee_id', '<i4'), ('Age', '<i4'), ('Experience', '<i4'), ('Region', '<U10'), ('Product', '<U15'), ('Sales', '<f8'), ('Unit_sold', '<i4'), ('Discount', '<f8'), ('Customer_Rating', '<f8')])

In [120]:
data[-5:]

array([(1096, 30,  1, 'West', 'Monitor',  86690., 27,  0.7 , 3.88),
       (1097, 36, 11, 'North', 'Mobile',  24499., 35, 24.43, 4.92),
       (1098, 36,  5, 'North', 'Mobile',  26295., 33,  8.46, 3.81),
       (1099, 47,  6, 'East', 'Laptop', 140885., 95,  3.54, 4.07),
       (1100, 34,  4, 'North', 'Mobile', 146071., 34, 20.9 , 4.24)],
      dtype=[('Employee_id', '<i4'), ('Age', '<i4'), ('Experience', '<i4'), ('Region', '<U10'), ('Product', '<U15'), ('Sales', '<f8'), ('Unit_sold', '<i4'), ('Discount', '<f8'), ('Customer_Rating', '<f8')])

### Boolean Filtering

In [121]:
condition = data['Sales'] > 140000

In [122]:
data[condition]

array([(1004, 42,  6, 'South', 'Printer', 146354., 91,  1.08, 4.51),
       (1009, 45,  3, 'North', 'Laptop', 145657., 85,  0.92, 4.98),
       (1045, 27,  8, 'West', 'Tablet', 144249., 38, 16.63, 3.6 ),
       (1073, 32, 15, 'West', 'Tablet', 140975., 42,  2.12, 2.78),
       (1084, 44, 13, 'North', 'Tablet', 146603., 45, 11.58, 3.44),
       (1099, 47,  6, 'East', 'Laptop', 140885., 95,  3.54, 4.07),
       (1100, 34,  4, 'North', 'Mobile', 146071., 34, 20.9 , 4.24)],
      dtype=[('Employee_id', '<i4'), ('Age', '<i4'), ('Experience', '<i4'), ('Region', '<U10'), ('Product', '<U15'), ('Sales', '<f8'), ('Unit_sold', '<i4'), ('Discount', '<f8'), ('Customer_Rating', '<f8')])

sale > 10000 and rating > 4

In [123]:
data[(data['Sales']>100000) & (data['Customer_Rating']>4)]

array([(1004, 42,  6, 'South', 'Printer', 146354., 91,  1.08, 4.51),
       (1007, 32, 12, 'West', 'Mobile', 107092., 44,  8.6 , 4.38),
       (1009, 45,  3, 'North', 'Laptop', 145657., 85,  0.92, 4.98),
       (1012, 43,  6, 'South', 'Laptop', 107455., 99, 10.81, 4.44),
       (1017, 42, 12, 'West', 'Laptop', 129751., 52, 18.69, 4.38),
       (1018, 54,  3, 'West', 'Laptop', 138906., 33,  2.56, 4.39),
       (1027, 28,  9, 'South', 'Monitor', 109045., 67, 23.86, 4.76),
       (1030, 39,  8, 'West', 'Printer', 100623., 41,  2.35, 4.88),
       (1033, 35, 11, 'North', 'Laptop', 113384., 70, 25.08, 4.08),
       (1039, 28, 13, 'North', 'Monitor', 111906., 49, 16.48, 4.48),
       (1054, 29,  3, 'East', 'Printer', 104896., 25,  1.22, 4.25),
       (1057, 42,  2, 'East', 'Mobile', 108614., 65, 14.23, 4.27),
       (1065, 22,  0, 'North', 'Printer', 132561., 44, 19.05, 4.97),
       (1083, 54, 11, 'East', 'Mobile', 132893., 61, 28.24, 4.91),
       (1086, 43,  1, 'North', 'Printer', 137796.

### Sale of East or west

In [124]:
condition = (data['Region'] == "East") | (data['Region'] =='West')

In [125]:
data[condition]

array([(1001, 50,  2, 'East', 'Tablet',  58623., 52, 11.27, 4.07),
       (1006, 44,  3, 'East', 'Mobile', 139937., 57, 16.28, 2.94),
       (1007, 32, 12, 'West', 'Mobile', 107092., 44,  8.6 , 4.38),
       (1008, 32, 15, 'East', 'Tablet',  70859., 37, 17.72, 4.52),
       (1010, 45, 13, 'East', 'Printer', 124095., 73,  1.12, 3.53),
       (1011, 24,  4, 'West', 'Laptop',  46309., 54, 24.68, 3.43),
       (1013, 23,  6, 'West', 'Tablet',  83734., 80,  3.81, 3.35),
       (1014, 45, 12, 'West', 'Printer',  90467., 60, 15.67, 4.83),
       (1015, 51, 14, 'West', 'Printer',  72662., 52, 23.1 , 4.65),
       (1017, 42, 12, 'West', 'Laptop', 129751., 52, 18.69, 4.38),
       (1018, 54,  3, 'West', 'Laptop', 138906., 33,  2.56, 4.39),
       (1019, 33, 12, 'West', 'Mobile',  32688., 40,  1.55, 2.76),
       (1021, 46,  6, 'West', 'Mobile',  57157., 39, 16.22, 3.76),
       (1023, 49,  2, 'West', 'Mobile', 126308., 26, 21.78, 3.3 ),
       (1024, 37,  5, 'West', 'Tablet',  72083., 86, 29.28,

### Record should not come from north

In [126]:
data[data['Region'] != "North"]

array([(1001, 50,  2, 'East', 'Tablet',  58623., 52, 11.27, 4.07),
       (1004, 42,  6, 'South', 'Printer', 146354., 91,  1.08, 4.51),
       (1005, 40,  0, 'South', 'Printer',  66717., 55, 13.97, 3.21),
       (1006, 44,  3, 'East', 'Mobile', 139937., 57, 16.28, 2.94),
       (1007, 32, 12, 'West', 'Mobile', 107092., 44,  8.6 , 4.38),
       (1008, 32, 15, 'East', 'Tablet',  70859., 37, 17.72, 4.52),
       (1010, 45, 13, 'East', 'Printer', 124095., 73,  1.12, 3.53),
       (1011, 24,  4, 'West', 'Laptop',  46309., 54, 24.68, 3.43),
       (1012, 43,  6, 'South', 'Laptop', 107455., 99, 10.81, 4.44),
       (1013, 23,  6, 'West', 'Tablet',  83734., 80,  3.81, 3.35),
       (1014, 45, 12, 'West', 'Printer',  90467., 60, 15.67, 4.83),
       (1015, 51, 14, 'West', 'Printer',  72662., 52, 23.1 , 4.65),
       (1016, 23, 10, 'South', 'Monitor', 118506., 87,  6.47, 3.57),
       (1017, 42, 12, 'West', 'Laptop', 129751., 52, 18.69, 4.38),
       (1018, 54,  3, 'West', 'Laptop', 138906., 33,

### index of the records where sale > 120000

In [128]:
indexes = np.where(data['Sales']>120000)

In [130]:
indexes

(array([ 3,  5,  8,  9, 16, 17, 22, 24, 28, 35, 42, 44, 47, 57, 64, 72, 75,
        78, 81, 82, 83, 85, 91, 98, 99]),)

In [129]:
data[indexes]

array([(1004, 42,  6, 'South', 'Printer', 146354., 91,  1.08, 4.51),
       (1006, 44,  3, 'East', 'Mobile', 139937., 57, 16.28, 2.94),
       (1009, 45,  3, 'North', 'Laptop', 145657., 85,  0.92, 4.98),
       (1010, 45, 13, 'East', 'Printer', 124095., 73,  1.12, 3.53),
       (1017, 42, 12, 'West', 'Laptop', 129751., 52, 18.69, 4.38),
       (1018, 54,  3, 'West', 'Laptop', 138906., 33,  2.56, 4.39),
       (1023, 49,  2, 'West', 'Mobile', 126308., 26, 21.78, 3.3 ),
       (1025, 36, 11, 'South', 'Tablet', 126081., 36, 15.49, 3.47),
       (1029, 30, 13, 'South', 'Monitor', 130078., 78, 13.17, 3.3 ),
       (1036, 23, 11, 'East', 'Mobile', 129893., 46,  5.2 , 3.32),
       (1043, 25,  6, 'West', 'Mobile', 132547., 80, 28.65, 2.64),
       (1045, 27,  8, 'West', 'Tablet', 144249., 38, 16.63, 3.6 ),
       (1048, 39,  0, 'North', 'Laptop', 126642., 83,  7.43, 2.79),
       (1058, 37,  6, 'North', 'Laptop', 120689., 72,  2.94, 2.7 ),
       (1065, 22,  0, 'North', 'Printer', 132561., 44

In [133]:
performance = np.where(data['Sales']>120000,"Excellent",
np.where(data['Sales']>100000,"Good","Needs Improvement"))

In [136]:
categories, counts = np.unique(performance,return_counts=True)

In [138]:
categories

array(['Excellent', 'Good', 'Needs Improvement'], dtype='<U17')

In [137]:
counts

array([25, 16, 59])

In [142]:
for category,count in zip(categories,counts):
    print(category,":",count)

Excellent : 25
Good : 16
Needs Improvement : 59


In [146]:
regions,counts = np.unique(data['Region'],return_counts=True)

In [147]:
for region,count in zip(regions,counts):
    print(f"{region} : {count}")

East : 20
North : 32
South : 22
West : 26


In [150]:
data['Sales'][data['Region']=="West"]

array([107092.,  46309.,  83734.,  90467.,  72662., 129751., 138906.,
        32688.,  57157., 126308.,  72083.,  85733.,  54698., 100623.,
        42671.,  62107., 106202., 132547., 144249.,  54754., 103879.,
        21802., 105981., 140975.,  62642.,  86690.])

In [155]:
for region in regions:
    region_sales = data['Sales'][data['Region']==region]
    print("-"*5,f"{region}' stat","-"*5)
    print(f"Total sale: {np.sum(region_sales)}")
    print(f"Average sale: {np.round(np.mean(region_sales),3)}")
    print(f"Minimum sale: {np.min(region_sales)}")
    print(f"Maximum sale: {np.max(region_sales)}")
    print()
    print()




----- East' stat -----
Total sale: 1860789.0
Average sale: 93039.45
Minimum sale: 22911.0
Maximum sale: 140885.0


----- North' stat -----
Total sale: 2622354.0
Average sale: 81948.562
Minimum sale: 22049.0
Maximum sale: 146603.0


----- South' stat -----
Total sale: 1725440.0
Average sale: 78429.091
Minimum sale: 28155.0
Maximum sale: 146354.0


----- West' stat -----
Total sale: 2262710.0
Average sale: 87027.308
Minimum sale: 21802.0
Maximum sale: 144249.0




In [158]:
prdcts,prdcnt = np.unique(data['Product'],return_counts=True)
print(prdcts,prdcnt)

for prd in prdcts:
    product_sales = data['Sales'][data['Product']==prd]
    print("-"*5,f"{prd}' stat","-"*5)
    print(f"Total sale: {np.sum(product_sales)}")
    print(f"Average sale: {np.round(np.mean(product_sales),3)}")
    print(f"Minimum sale: {np.min(product_sales)}")
    print(f"Maximum sale: {np.max(product_sales)}")
    print()
    print()


['Laptop' 'Mobile' 'Monitor' 'Printer' 'Tablet'] [18 25 14 22 21]
----- Laptop' stat -----
Total sale: 1615559.0
Average sale: 89753.278
Minimum sale: 28680.0
Maximum sale: 145657.0


----- Mobile' stat -----
Total sale: 2002301.0
Average sale: 80092.04
Minimum sale: 22811.0
Maximum sale: 146071.0


----- Monitor' stat -----
Total sale: 1201502.0
Average sale: 85821.571
Minimum sale: 21802.0
Maximum sale: 130078.0


----- Printer' stat -----
Total sale: 1883045.0
Average sale: 85592.955
Minimum sale: 22049.0
Maximum sale: 146354.0


----- Tablet' stat -----
Total sale: 1768886.0
Average sale: 84232.667
Minimum sale: 35708.0
Maximum sale: 146603.0


