In [1]:
import numpy as np

In [3]:
age = np.array([34,32,28,29,31])

In [4]:
arr = np.arange(23,120)

# indexing and slicing

In [8]:
arr

array([ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119])

In [7]:
arr[0],arr[2]

(np.int64(23), np.int64(25))

In [9]:
len(arr)

97

In [10]:
arr[78]

np.int64(101)

In [14]:
age[0:3]

array([34, 32, 28])

In [17]:
age[2:4]

array([28, 29])

In [18]:
matrix = np.array(
    [
        [34,78,29],
        [34,56,23],
        [90,78,23]
    ]
)

In [21]:
matrix.ndim

2

In [26]:
age

array([34, 32, 28, 29, 31])

In [42]:
matrix[1][0]

np.int64(34)

In [43]:
matrix

array([[34, 78, 29],
       [34, 56, 23],
       [90, 78, 23]])

In [49]:
matrix[1:,0:2]

array([[34, 56],
       [90, 78]])

In [52]:
age

array([34, 32, 28, 29, 31])

In [51]:
age[:4]

array([34, 32, 28, 29])

# Boolean filtering

In [53]:
age

array([34, 32, 28, 29, 31])

In [56]:
age

array([34, 32, 28, 29, 31])

In [57]:
age > 30

array([ True,  True, False, False,  True])

In [ ]:
age[age > 30]

array([34, 32, 31])

In [61]:
age

array([34, 32, 28, 29, 31])

In [60]:
age[[False, True, False, False, True]]

array([32, 31])

fetch all the element those are even / odd

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False])

In [67]:
arr % 2 != 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True])

In [66]:
arr[arr % 2 != 0]

array([ 23,  25,  27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,
        49,  51,  53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,
        75,  77,  79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99,
       101, 103, 105, 107, 109, 111, 113, 115, 117, 119])

## the number should greater than 67 and should be even

In [68]:
(arr % 2 == 0 ) & (arr > 67)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False])

In [69]:
arr[(arr % 2 == 0 ) & (arr > 67)]

array([ 68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,
        94,  96,  98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

In [ ]:
arr[~(arr % 2 == 0 ) | (arr > 67)]

array([ 23,  25,  27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,
        49,  51,  53,  55,  57,  59,  61,  63,  65,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [76]:
age[~(age > 30)]

array([28, 29])

In [85]:
arr

array([ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119])

In [84]:
arr[::3]

array([ 23,  26,  29,  32,  35,  38,  41,  44,  47,  50,  53,  56,  59,
        62,  65,  68,  71,  74,  77,  80,  83,  86,  89,  92,  95,  98,
       101, 104, 107, 110, 113, 116, 119])

In [87]:
arr

array([ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119])

In [ ]:
arr[::-2]

array([119, 117, 115, 113, 111, 109, 107, 105, 103, 101,  99,  97,  95,
        93,  91,  89,  87,  85,  83,  81,  79,  77,  75,  73,  71,  69,
        67,  65,  63,  61,  59,  57,  55,  53,  51,  49,  47,  45,  43,
        41,  39,  37,  35,  33,  31,  29,  27,  25,  23])

In [88]:
age

array([34, 32, 28, 29, 31])

In [90]:
age[::-2]

array([31, 28, 34])

In [91]:
matrix

array([[34, 78, 29],
       [34, 56, 23],
       [90, 78, 23]])

In [93]:
matrix[::-1,::-1]

array([[23, 78, 90],
       [23, 56, 34],
       [29, 78, 34]])

In [95]:
matrix

array([[34, 78, 29],
       [34, 56, 23],
       [90, 78, 23]])

In [94]:
matrix.T

array([[34, 34, 90],
       [78, 56, 78],
       [29, 23, 23]])